### ISSUE TITLE
Access to absolute path doesn't work when hosted on Pterodactyl Paper server

### ISSUE THREAD

**Issue by ManatorDE** [jpenilla/squaremap#76]
Files can't be accessed when running squaremap  on pterodactyl and on an external host.
No matter which permissions I give the files or which owner / group they have it always produces the errors seen in the log below!

[latest.log](https://github.com/jpenilla/squaremap/files/9509085/latest.log)

Can anyone help me here?

Thanks!

**Comment by jpenilla** [comment]
Ptero uses docker containers iirc, so you'll need to do something to allow access to the directory on the host fs. This is not really a bug report and more a support question, so it belongs on the discord (linked in readme) rather than GitHub issues, however ptero's discord might be a better place for this question.
